//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zalicznie_semestralne
{
    using System;
    using System.Collections.Generic;
    
    public partial class dostawa
    {
        public int Id_dostawy { get; set; }
        public string sklep { get; set; }
        public string nazawa_ulicy { get; set; }
        public string cena_dostwy_do_20km { get; set; }
        public string cena_dostwy_powyzej_20km { get; set; }
    }
}
