//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zalicznie_semestralne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sklep_internetowyEntities : DbContext
    {
        public sklep_internetowyEntities()
            : base("name=sklep_internetowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dostawa> dostawa { get; set; }
        public virtual DbSet<produkty> produkty { get; set; }
        public virtual DbSet<shop> shop { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<zamowienie> zamowienie { get; set; }
    }
}
