//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zalicznie_semestralne
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkty
    {
        public int Id_produkty { get; set; }
        public string producent { get; set; }
        public string model { get; set; }
        public string cena { get; set; }
    }
}
