//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zalicznie_semestralne
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public int Id_shop { get; set; }
        public string nazwa_sklpu { get; set; }
        public string miejscowasc { get; set; }
        public string ulica { get; set; }
    }
}
