//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zalicznie_semestralne
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienie
    {
        public int Id_zamowienia { get; set; }
        public string dane_klijenta_ { get; set; }
        public string sklep { get; set; }
        public string nazwa_produktu { get; set; }
        public string nazwa_modelu { get; set; }
        public string cena { get; set; }
    }
}
